### ISSUE TITLE
Highlight after yank-code plugin call?

### ISSUE THREAD

**Issue by danbruegge** [machakann/vim-highlightedyank#37]
Hi,
is there a way to highlight the yanked lines after calling a yank plugin? For example https://github.com/AaronLasseigne/yank-code.

Maybe something like:
```vim
vmap <leader>y :YankCode && HightlightedyankHighlight <CR>
```

**Comment by machakann** [comment]
Hi, this is actually difficult because it is not always easy to recognize the area where the yank-code plugin yanked. However, only if limited to the key mapping you shown, it is possible after you update vim-highlightedyank (https://github.com/machakann/vim-highlightedyank/commit/26a2ecc1ac08462680074a721c265e42b1c545ba):

```vim
xmap <Leader>y :YankCode<CR>:call highlightedyank#highlight#add('HighlightedyankRegion', getpos("'<"), getpos("'>"), 'V', 1000)<CR>
```

As you can see, it's a bit hacky way and may not be what you want...

**Comment by danbruegge** [comment]
This is looking good and it works well. Thanks. :)
