### ISSUE TITLE
Crashes neovim nightly

### ISSUE THREAD

**Issue by bo5o** [machakann/vim-highlightedyank#44]
With this plugin enabled, neovim crashes to the point where I can't recover it. It throws the following error:

<img width="857" alt="bug_report_highlighted_yank" src="https://user-images.githubusercontent.com/32486983/84662465-200eb000-af1c-11ea-897c-a53bf59bd6e8.PNG">

### Version

NVIM v0.5.0-563-ge628a05b5

**Comment by machakann** [comment]
It seems an internal error of nvim appeared; there is nothing to be able to do from the plugin side. It should be submitted to neovim issue tracker, I believe. (Since it is an assertion error, anyway something unexpected happened inside.)

Additionally, they would be happy if you could provide step-by-step procedure to reproduce the problem.

**Comment by machakann** [comment]
Probably, related?
https://github.com/neovim/neovim/issues/12430
https://github.com/neovim/neovim/pull/12436

**Comment by bo5o** [comment]
Thank you. The PR you mentioned seems to fix the issue.

**Comment by bo5o** [comment]
PR has been merged and fixes the issue.

**Comment by machakann** [comment]
Glad to hear that!
